### PR TITLE
Added a pixel art Splash Screen 

### PR DESCRIPTION
**Pull request by reapersanta**
Pixel art Splashscreen I made (so that the pixel look remains consistent :> )

### CODE REVIEW

**Comment by Lachee** [comment]
This looks awesome! Great stuff :D

**Comment by SolarLune** [comment]
Whoops! I forgot to comment on this. 

I really like this splashscreen; thanks for creating it! I also appreciate the time you took to make it. However, I don't think we should add assets like splashscreens via PRs directly, though I do welcome community contributions like these and do think it would be cool to have community-made assets like splashscreens or themes in MP.

I think I'll have to do some thinking about community contributions, and ways we could more effectively weave them into MasterPlan without having to merge things into the codebase directly, as that bloats the overall size of MasterPlan. 

Maybe I could grab assets like splashscreens and themes and push them onto a web server for MP to download and use from within the program? It's something to think about, anyway, and I hope you'll keep an eye on the forums for a discussion in this regard.

**Comment by Lachee** [comment]
While that might be a smart idea, the splash screen needs to be fast to load so it doesn't hold up users from using MP.

**Comment by SolarLune** [comment]
Yes, that is indeed true. It's a discussion for another place, in my opinion, so I'll close this PR.

**Pull request closed without merging**
